name = "Thrush"
uuid = "1ddded22-6fc6-4ca9-aa11-2d3393dfe105"
authors = ["Peter Ahrens"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
